<#
.SYNOPSIS
  Detect the local Altium Designer installation and write <repo>\Environment.local.props.

.DESCRIPTION
  Run this once after cloning the repository on a new machine (and again after upgrading Altium).
  It reads HKLM\SOFTWARE\Altium\Builds, picks the newest installed Altium Designer, and writes the
  MSBuild property file that Directory.Build.props imports. The tool scripts read the same file.

  The file is git-ignored on purpose: it is the ONLY place with machine-specific absolute paths.
  Edit it by hand when auto-detection picks the wrong install or when optional roots differ.

.PARAMETER Print
  Only print what would be written; do not touch Environment.local.props.

.PARAMETER CopyExamples
  Copy the Altium example project(s) named in -Examples into AltiumMcpTestProjectsRoot (skips
  existing folders). Gives a scratch copy that live tests may compile/modify.

.EXAMPLE
  .\tools\Detect-AltiumEnvironment.ps1
  .\tools\Detect-AltiumEnvironment.ps1 -CopyExamples
  .\tools\Detect-AltiumEnvironment.ps1 -Print
#>
[CmdletBinding()]
param(
    [switch]$Print,
    [switch]$CopyExamples,
    [string[]]$Examples = @('Bluetooth Sentinel'),
    [string]$ExtensionExamplesRoot = '',
    [string]$DisasmRoot = '',
    [string]$TestProjectsRoot = ''
)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\AltiumEnvironment.ps1"

$builds = @(Get-AltiumBuildsFromRegistry)
if ($builds.Count -eq 0) {
    Write-Warning 'No installed Altium Designer found in HKLM\SOFTWARE\Altium\Builds. Falling back to defaults; edit Environment.local.props by hand.'
} else {
    Write-Host "Installed Altium Designer builds (newest first):"
    $builds | ForEach-Object { Write-Host ("  {0}  {1}  {2}" -f $_.FullBuild, $_.ProfileGuid, $_.ProgramsHome) }
}

# Detect ignoring any existing props so the file reflects the machine, then let explicit args win.
$e = Get-AltiumEnvironment -IgnoreLocalProps
$existing = Read-AltiumEnvironmentProps $e.LocalPropsPath

function Pick([string]$arg, [string]$existingValue, [string]$detected) {
    if ($arg) { return $arg }
    if ($existingValue) { return $existingValue }   # keep manual edits for optional roots
    return $detected
}

$values = [ordered]@{
    AltiumProductVersion        = $e.AltiumProductVersion
    AltiumProfileGuid           = $e.AltiumProfileGuid
    AltiumProgramsHome          = $e.AltiumProgramsHome
    AltiumDocumentsHome         = $e.AltiumDocumentsHome
    AltiumMcpTestProjectsRoot   = Pick $TestProjectsRoot      $existing['AltiumMcpTestProjectsRoot']   $e.AltiumMcpTestProjectsRoot
    AltiumExtensionExamplesRoot = Pick $ExtensionExamplesRoot $existing['AltiumExtensionExamplesRoot'] $e.AltiumExtensionExamplesRoot
    AltiumDisasmRoot            = Pick $DisasmRoot            $existing['AltiumDisasmRoot']            $e.AltiumDisasmRoot
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('<?xml version="1.0" encoding="utf-8"?>')
[void]$sb.AppendLine('<!--')
[void]$sb.AppendLine('  Machine-specific environment for AltiumExtensionMCP. Generated by tools\Detect-AltiumEnvironment.ps1')
[void]$sb.AppendLine("  on $env:COMPUTERNAME at $(Get-Date -Format 'yyyy-MM-dd HH:mm'). Git-ignored. Imported by Directory.Build.props and read")
[void]$sb.AppendLine('  by tools\*.ps1. Derived paths (SDK, System, X2.EXE, deploy dir) come from AltiumProgramsHome/AltiumProfileGuid;')
[void]$sb.AppendLine('  add AltiumSdkHome / AltiumSystemHome / AltiumExe / AltiumExtensionDeployDir here to override them explicitly.')
[void]$sb.AppendLine('  Documentation: docs/ENVIRONMENT.md')
[void]$sb.AppendLine('-->')
[void]$sb.AppendLine('<Project>')
[void]$sb.AppendLine('  <PropertyGroup>')
foreach ($k in $values.Keys) {
    $v = [System.Security.SecurityElement]::Escape([string]$values[$k])
    [void]$sb.AppendLine("    <$k>$v</$k>")
}
# Preserve explicit overrides a human added earlier.
foreach ($k in 'AltiumProfileRoot','AltiumSdkHome','AltiumSystemHome','AltiumExe','AltiumExtensionDeployDir') {
    if ($existing.ContainsKey($k) -and $existing[$k]) {
        $v = [System.Security.SecurityElement]::Escape([string]$existing[$k])
        [void]$sb.AppendLine("    <$k>$v</$k>")
    }
}
[void]$sb.AppendLine('  </PropertyGroup>')
[void]$sb.AppendLine('</Project>')

if ($Print) {
    Write-Host "`n--- $($e.LocalPropsPath) (not written) ---"
    Write-Host $sb.ToString()
} else {
    Set-Content -Path $e.LocalPropsPath -Value $sb.ToString() -Encoding UTF8
    Write-Host "`nWrote $($e.LocalPropsPath)"
}

$final = Get-AltiumEnvironment
Write-Host "`nResolved environment ($($final.ResolvedFrom)):"
$allOk = Test-AltiumEnvironment -Environment $final

if ($CopyExamples) {
    foreach ($name in $Examples) {
        $src = Join-Path $final.AltiumExamplesRoot $name
        $dst = Join-Path $final.AltiumMcpTestProjectsRoot $name
        if (-not (Test-Path $src)) { Write-Warning "Example not found: $src"; continue }
        if (Test-Path $dst) { Write-Host "Test project already present: $dst"; continue }
        New-Item -ItemType Directory -Path $final.AltiumMcpTestProjectsRoot -Force | Out-Null
        Copy-Item $src $dst -Recurse
        Write-Host "Copied example '$name' -> $dst"
    }
}

if (-not $allOk) {
    Write-Warning 'Some required paths are missing. Fix Environment.local.props (see docs/ENVIRONMENT.md) before building the extension.'
    exit 1
}

